services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - backend-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: KLGRAM-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend-network

networks:
  backend-network: